version: '3.1'

services:

    demo-mysql-master:
        image: mysql:5.7
        container_name: demo-mysql-master
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mysql-master/my.cnf:/etc/mysql/my.cnf
            - ./mysql-master/sql:/docker-entrypoint-initdb.d
#           - ../binlogdemo_data/master:/var/lib/mysql
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: demo
            MYSQL_USER: master
            MYSQL_PASSWORD: password

    demo-mysql-slave:
        image: mysql:5.7
        container_name: demo-mysql-slave
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - ./mysql-slave/my.cnf:/etc/mysql/my.cnf
            - ./mysql-slave/sql:/docker-entrypoint-initdb.d
#           - ../binlogdemo_data/slave:/var/lib/mysql
        environment:
            TZ: Asia/Shanghai
            MYSQL_ROOT_PASSWORD: password
            MYSQL_DATABASE: demo
            MYSQL_USER: slave
            MYSQL_PASSWORD: password

